version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: db-intuitive-care
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}   
    ports:
      - "3306:3306"                     
    volumes:
      - ./mysql_data:/var/lib/mysql     
      - ./3-TesteCriacaoBD/csv_files:/var/lib/mysql-files
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

